In [202]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn as sk
## %matplotlib inline

In [203]:
WashCountyVT = pd.read_csv('WashingtonCountyVT2015CensusData.csv')
WashCountyVT = WashCountyVT.drop(['State', 'County', 'Unnamed: 0', 'CensusTract'], axis=1)
WashCountyVT.head(20)

,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,Pacific,Citizen,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
0,4385,2190,2195,1.6,94.3,0.8,0.1,0.6,0.0,3313,...,4.9,0.8,10.0,29.4,2193,68.2,14.6,16.8,0.3,6.8
1,2395,1246,1149,3.0,92.9,0.0,0.0,0.6,0.0,1945,...,0.8,0.5,10.1,30.3,1326,67.0,19.5,13.0,0.5,4.3
2,2811,1416,1395,1.3,94.1,0.6,0.4,0.6,0.0,2118,...,2.6,0.6,9.8,28.4,1568,63.9,18.4,17.7,0.0,4.0
3,5089,2556,2533,0.9,96.1,0.0,0.0,0.9,0.0,4180,...,5.3,0.1,2.0,23.0,3108,75.5,17.2,7.2,0.0,6.4
4,3060,1549,1511,3.0,93.4,0.0,2.3,0.9,0.0,2428,...,1.3,1.4,5.2,25.3,1778,72.1,20.5,7.4,0.0,3.6
5,2850,1399,1451,0.7,93.4,0.5,0.3,2.4,0.2,2318,...,1.5,1.4,4.8,20.3,1312,70.0,20.1,9.8,0.0,7.1
6,2264,1091,1173,2.5,91.4,1.9,0.0,1.8,0.0,1793,...,19.8,1.0,7.0,17.8,1209,68.1,20.8,11.1,0.0,11.4
7,1462,718,744,0.9,96.4,0.0,0.0,1.0,0.0,1149,...,15.6,0.6,6.0,16.8,722,66.3,24.0,9.7,0.0,6.7
8,2311,999,1312,0.0,95.0,1.8,0.0,0.0,0.0,1840,...,24.6,3.3,11.2,17.1,1239,70.0,21.1,6.6,2.3,2.3
9,1675,782,893,1.8,95.0,0.1,0.0,1.7,0.0,1304,...,4.7,1.2,6.8,18.0,829,67.4,25.2,6.6,0.7,2.0
10,2610,1169,1441,5.3,92.1,1.1,0.0,0.2,0.0,2073,...,1.9,1.2,7.4,21.0,1414,69.0,22.5,8.5,0.0,3.3
11,4154,1907,2247,0.0,97.8,0.0,0.0,0.0,0.0,3204,...,6.2,0.0,4.4,16.9,2100,73.0,20.6,5.5,0.9,5.6
12,4731,2113,2618,3.0,90.2,4.8,1.1,0.6,0.0,3507,...,3.2,6.9,2.1,21.3,2237,83.5,11.4,5.1,0.0,7.8
13,3902,1878,2024,1.1,96.6,0.3,0.0,0.0,0.0,2988,...,0.0,0.4,8.3,24.7,2164,71.7,17.3,10.3,0.7,5.5
14,3988,2091,1897,3.0,94.5,0.6,0.0,0.4,0.0,3137,...,8.0,0.7,3.9,19.1,2307,80.6,16.0,3.4,0.0,2.9
15,6898,3817,3081,3.0,93.7,0.8,0.0,1.5,0.0,5849,...,10.9,1.0,5.5,22.1,3536,68.5,23.3,8.0,0.2,2.5
16,1615,842,773,0.0,98.1,0.0,0.0,0.7,0.0,1279,...,5.0,2.3,11.9,25.2,961,77.7,9.1,13.2,0.0,1.3
17,1701,799,902,1.3,95.4,0.3,0.4,0.4,0.0,1398,...,4.2,0.8,15.3,25.8,1055,72.3,15.8,11.8,0.0,1.9
18,1231,620,611,0.0,97.4,0.3,0.0,1.0,0.0,918,...,3.1,1.9,16.8,24.1,716,76.1,12.6,10.6,0.7,1.8

In [204]:
WashCountyVT.describe()

,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,Pacific,Citizen,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
count,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,...,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000
mean,3112.210526,1535.894737,1576.315789,1.705263,94.621053,0.731579,0.242105,0.805263,0.010526,2460.052632,...,6.505263,1.373684,7.815789,22.452632,1672.315789,71.626316,18.421053,9.594737,0.331579,4.589474
std,1487.121776,796.054779,710.167277,1.425745,2.154473,1.141662,0.567955,0.655298,0.045883,1222.384940,...,6.705675,1.550212,4.075573,4.297851,785.592986,5.106950,4.368775,3.789382,0.570626,2.640895
min,1231.000000,620.000000,611.000000,0.000000,90.200000,0.000000,0.000000,0.000000,0.000000,918.000000,...,0.000000,0.000000,2.000000,16.800000,716.000000,63.900000,9.100000,3.400000,0.000000,1.300000
25%,1982.500000,920.500000,1025.500000,0.800000,93.400000,0.000000,0.000000,0.400000,0.000000,1595.500000,...,2.250000,0.600000,5.000000,18.550000,1132.000000,68.150000,15.900000,6.900000,0.000000,2.400000
50%,2811.000000,1399.000000,1441.000000,1.300000,94.500000,0.300000,0.000000,0.600000,0.000000,2118.000000,...,4.700000,1.000000,7.000000,22.100000,1414.000000,70.000000,19.500000,9.700000,0.000000,4.000000
75%,4071.000000,1999.000000,2109.500000,3.000000,96.250000,0.800000,0.200000,1.000000,0.000000,3170.500000,...,7.100000,1.400000,10.050000,25.250000,2178.500000,74.250000,20.950000,11.450000,0.600000,6.550000
max,6898.000000,3817.000000,3081.000000,5.300000,98.100000,4.800000,2.300000,2.400000,0.200000,5849.000000,...,24.600000,6.900000,16.800000,30.300000,3536.000000,83.500000,25.200000,17.700000,2.300000,11.400000

In [205]:
WashCountyVT.mean()

TotalPop            3112.210526
Men                 1535.894737
Women               1576.315789
Hispanic               1.705263
White                 94.621053
Black                  0.731579
Native                 0.242105
Asian                  0.805263
Pacific                0.010526
Citizen             2460.052632
Income             61052.684211
IncomeErr           8059.947368
IncomePerCap       32350.105263
IncomePerCapErr     3792.263158
Poverty                9.394737
ChildPoverty          11.568421
Professional          45.431579
Service               14.973684
Office                23.284211
Construction           8.610526
Production             7.726316
Drive                 73.231579
Carpool                9.647368
Transit                1.447368
Walk                   6.505263
OtherTransp            1.373684
WorkAtHome             7.815789
MeanCommute           22.452632
Employed            1672.315789
PrivateWork           71.626316
PublicWork            18.421053
SelfEmployed           9.594737
FamilyWork             0.331579
Unemployment           4.589474
dtype: float64

In [206]:
WashCountyVT.shape

(19, 34)

In [207]:
WashCountyVT.dtypes

TotalPop             int64
Men                  int64
Women                int64
Hispanic           float64
White              float64
Black              float64
Native             float64
Asian              float64
Pacific            float64
Citizen              int64
Income             float64
IncomeErr          float64
IncomePerCap       float64
IncomePerCapErr    float64
Poverty            float64
ChildPoverty       float64
Professional       float64
Service            float64
Office             float64
Construction       float64
Production         float64
Drive              float64
Carpool            float64
Transit            float64
Walk               float64
OtherTransp        float64
WorkAtHome         float64
MeanCommute        float64
Employed             int64
PrivateWork        float64
PublicWork         float64
SelfEmployed       float64
FamilyWork         float64
Unemployment       float64
dtype: object

In [208]:
EthnicWashCountyVT = pd.DataFrame(data = WashCountyVT, columns=['TotalPop', 'Men', 'Women', 'White', 'Hispanic', 'Black', 'Native', 'Asian','Pacific','Citizen','Income','Employed','PrivateWork','SelfEmployed','Unemployment', 'Professional', 'Service', 'Office', 'Construction', 'Production'])
EthnicWashCountyVT.head(19)

,TotalPop,Men,Women,White,Hispanic,Black,Native,Asian,Pacific,Citizen,Income,Employed,PrivateWork,SelfEmployed,Unemployment,Professional,Service,Office,Construction,Production
0,4385,2190,2195,94.3,1.6,0.8,0.1,0.6,0.0,3313,51500.0,2193,68.2,16.8,6.8,39.3,13.6,23.3,15.1,8.7
1,2395,1246,1149,92.9,3.0,0.0,0.0,0.6,0.0,1945,59048.0,1326,67.0,13.0,4.3,41.7,14.6,24.0,13.8,6.0
2,2811,1416,1395,94.1,1.3,0.6,0.4,0.6,0.0,2118,60163.0,1568,63.9,17.7,4.0,49.1,12.1,18.4,12.5,8.0
3,5089,2556,2533,96.1,0.9,0.0,0.0,0.9,0.0,4180,60400.0,3108,75.5,7.2,6.4,44.3,16.3,20.1,11.0,8.4
4,3060,1549,1511,93.4,3.0,0.0,2.3,0.9,0.0,2428,70556.0,1778,72.1,7.4,3.6,44.3,16.8,20.4,9.7,8.8
5,2850,1399,1451,93.4,0.7,0.5,0.3,2.4,0.2,2318,56941.0,1312,70.0,9.8,7.1,39.6,15.9,23.6,11.7,9.1
6,2264,1091,1173,91.4,2.5,1.9,0.0,1.8,0.0,1793,67550.0,1209,68.1,11.1,11.4,66.5,13.2,15.3,1.8,3.1
7,1462,718,744,96.4,0.9,0.0,0.0,1.0,0.0,1149,58375.0,722,66.3,9.7,6.7,53.5,15.7,24.4,3.7,2.8
8,2311,999,1312,95.0,0.0,1.8,0.0,0.0,0.0,1840,53065.0,1239,70.0,6.6,2.3,53.2,13.6,20.7,4.6,7.9
9,1675,782,893,95.0,1.8,0.1,0.0,1.7,0.0,1304,58448.0,829,67.4,6.6,2.0,52.5,9.8,27.6,5.1,5.1
10,2610,1169,1441,92.1,5.3,1.1,0.0,0.2,0.0,2073,66324.0,1414,69.0,8.5,3.3,53.3,9.7,21.8,6.8,8.4
11,4154,1907,2247,97.8,0.0,0.0,0.0,0.0,0.0,3204,36828.0,2100,73.0,5.5,5.6,38.0,14.6,32.6,6.5,8.4
12,4731,2113,2618,90.2,3.0,4.8,1.1,0.6,0.0,3507,46780.0,2237,83.5,5.1,7.8,33.4,17.5,28.9,5.8,14.4
13,3902,1878,2024,96.6,1.1,0.3,0.0,0.0,0.0,2988,69696.0,2164,71.7,10.3,5.5,39.6,13.3,31.2,8.0,7.9
14,3988,2091,1897,94.5,3.0,0.6,0.0,0.4,0.0,3137,59250.0,2307,80.6,3.4,2.9,34.1,18.4,25.1,8.2,14.2
15,6898,3817,3081,93.7,3.0,0.8,0.0,1.5,0.0,5849,69358.0,3536,68.5,8.0,2.5,41.0,16.8,23.4,9.4,9.4
16,1615,842,773,98.1,0.0,0.0,0.0,0.7,0.0,1279,65219.0,961,77.7,13.2,1.3,42.7,20.2,23.3,11.1,2.7
17,1701,799,902,95.4,1.3,0.3,0.4,0.4,0.0,1398,70500.0,1055,72.3,11.8,1.9,44.7,18.6,22.5,8.7,5.5
18,1231,620,611,97.4,0.0,0.3,0.0,1.0,0.0,918,80000.0,716,76.1,10.6,1.8,52.4,13.8,15.8,10.1,8.0

In [209]:
EthnicWashCountyVT['WhiteTotalPop'] = round(EthnicWashCountyVT['TotalPop'] * (EthnicWashCountyVT['White']* .01)).astype(int)

In [210]:
EthnicWashCountyVT['WhiteMaleTotalPop'] = round(EthnicWashCountyVT['Men'] * (EthnicWashCountyVT['White']* .01)).astype(int)

In [211]:
EthnicWashCountyVT['WhiteFemaleTotalPop'] = round(EthnicWashCountyVT['Women'] * (EthnicWashCountyVT['White']* .01)).astype(int)

In [212]:
EthnicWashCountyVT['HispanicTotalPop'] = round(EthnicWashCountyVT['TotalPop'] * (EthnicWashCountyVT['Hispanic']* .01)).astype(int)

In [213]:
EthnicWashCountyVT['HispanicMaleTotalPop'] = round(EthnicWashCountyVT['Men'] * (EthnicWashCountyVT['Hispanic']* .01)).astype(int)

In [214]:
EthnicWashCountyVT['HispanicFemaleTotalPop'] = round(EthnicWashCountyVT['Women'] * (EthnicWashCountyVT['Hispanic']* .01)).astype(int)

In [215]:
EthnicWashCountyVT['BlackTotalPop'] = round(EthnicWashCountyVT['TotalPop'] * (EthnicWashCountyVT['Black'] * .01)).astype(int)

In [216]:
EthnicWashCountyVT['BlackMaleTotalPop'] = round(EthnicWashCountyVT['Men'] * (EthnicWashCountyVT['Black']* .01)).astype(int)

In [217]:
EthnicWashCountyVT['BlackFemaleTotalPop'] = round(EthnicWashCountyVT['Women'] * (EthnicWashCountyVT['Black']* .01)).astype(int)

In [218]:
EthnicWashCountyVT['NativeTotalPop'] = round(EthnicWashCountyVT['TotalPop'] * (EthnicWashCountyVT['Native']* .01)).astype(int)

In [219]:
EthnicWashCountyVT['NativeMaleTotalPop'] = round(EthnicWashCountyVT['Men'] * (EthnicWashCountyVT['Native']* .01)).astype(int)

In [220]:
EthnicWashCountyVT['NativeFemaleTotalPop'] = round(EthnicWashCountyVT['Women'] * (EthnicWashCountyVT['Native']* .01)).astype(int)

In [221]:
EthnicWashCountyVT['AsianTotalPop'] = round(EthnicWashCountyVT['TotalPop'] * (EthnicWashCountyVT['Asian']* .01)).astype(int)

In [222]:
EthnicWashCountyVT['AsianMaleTotalPop'] = round(EthnicWashCountyVT['Men'] * (EthnicWashCountyVT['Asian']* .01)).astype(int)

In [223]:
EthnicWashCountyVT['AsianFemaleTotalPop'] = round(EthnicWashCountyVT['Women'] * (EthnicWashCountyVT['Asian']* .01)).astype(int)

In [224]:
EthnicWashCountyVT['PacificTotalPop'] = round(EthnicWashCountyVT['TotalPop'] * (EthnicWashCountyVT['Pacific'] * .01)).astype(int)

In [225]:
EthnicWashCountyVT['PacificMaleTotalPop'] = round(EthnicWashCountyVT['Men'] * (EthnicWashCountyVT['Pacific']* .01)).astype(int)

In [226]:
EthnicWashCountyVT['PacificFemaleTotalPop'] = round(EthnicWashCountyVT['Women'] * (EthnicWashCountyVT['Pacific']* .01)).astype(int)

In [227]:
EthnicWashCountyVT['TotalMalePercentage'] = (EthnicWashCountyVT['Men'] / EthnicWashCountyVT['TotalPop'])

In [228]:
EthnicWashCountyVT['TotalFemalePercentage'] = (EthnicWashCountyVT['Women'] / EthnicWashCountyVT['TotalPop'])

In [229]:
EthnicWashCountyVT['TotalWhitePopPercentage'] = (EthnicWashCountyVT['WhiteTotalPop'] / EthnicWashCountyVT['TotalPop'])

In [230]:
EthnicWashCountyVT['TotalWhiteMalePercentage'] = (EthnicWashCountyVT['WhiteMaleTotalPop'] / EthnicWashCountyVT['TotalPop'])

In [231]:
EthnicWashCountyVT['TotalWhiteFemalePercentage'] = (EthnicWashCountyVT['WhiteFemaleTotalPop'] / EthnicWashCountyVT['TotalPop'])

In [232]:
EthnicWashCountyVT['TotalHispanicPopPercentage'] = (EthnicWashCountyVT['HispanicTotalPop'] / EthnicWashCountyVT['TotalPop'])

In [233]:
EthnicWashCountyVT['TotalHispanicMalePercentage'] = (EthnicWashCountyVT['HispanicMaleTotalPop'] / EthnicWashCountyVT['TotalPop'])

In [234]:
EthnicWashCountyVT['TotalHispanicFemalePercentage'] = (EthnicWashCountyVT['HispanicFemaleTotalPop'] / EthnicWashCountyVT['TotalPop'])

In [235]:
EthnicWashCountyVT['TotalBlackPopPercentage'] = (EthnicWashCountyVT['BlackTotalPop'] / EthnicWashCountyVT['TotalPop'])

In [236]:
EthnicWashCountyVT['TotalBlackMalePercentage'] = (EthnicWashCountyVT['BlackMaleTotalPop'] / EthnicWashCountyVT['TotalPop'])

In [237]:
EthnicWashCountyVT['TotalBlackFemalePercentage'] = (EthnicWashCountyVT['BlackFemaleTotalPop'] / EthnicWashCountyVT['TotalPop'])

In [238]:
EthnicWashCountyVT['TotalNativePercentage'] = (EthnicWashCountyVT['NativeTotalPop'] / EthnicWashCountyVT['TotalPop'])

In [239]:
EthnicWashCountyVT['TotalAsianPopPercentage'] = (EthnicWashCountyVT['AsianTotalPop'] / EthnicWashCountyVT['TotalPop'])

In [240]:
EthnicWashCountyVT['TotalAsianMalePercentage'] = (EthnicWashCountyVT['AsianMaleTotalPop'] / EthnicWashCountyVT['TotalPop'])

In [241]:
EthnicWashCountyVT['TotalAsianFemalePercentage'] = (EthnicWashCountyVT['AsianFemaleTotalPop'] / EthnicWashCountyVT['TotalPop'])

In [242]:
EthnicWashCountyVT['TotalPacificPopPercentage'] = (EthnicWashCountyVT['PacificTotalPop'] / EthnicWashCountyVT['TotalPop'])

In [243]:
EthnicWashCountyVT['TotalPacificMalePercentage'] = (EthnicWashCountyVT['PacificMaleTotalPop'] / EthnicWashCountyVT['TotalPop'])

In [244]:
EthnicWashCountyVT['TotalPacificFemalePercentage'] = (EthnicWashCountyVT['PacificFemaleTotalPop'] / EthnicWashCountyVT['TotalPop'])

In [245]:
EthnicWashCountyVT['NonCitizen'] = (EthnicWashCountyVT['TotalPop'] - EthnicWashCountyVT['Citizen'])

In [246]:
EthnicWashCountyVT['CitizenPercentage'] = (EthnicWashCountyVT['Citizen'] / EthnicWashCountyVT['TotalPop'])

In [247]:
EthnicWashCountyVT['NonCitizenPercentage'] = (EthnicWashCountyVT['NonCitizen'] / EthnicWashCountyVT['TotalPop'])

In [248]:
EthnicWashCountyVT['EmployedPct'] = (EthnicWashCountyVT['Employed'] / EthnicWashCountyVT['TotalPop'])

In [249]:
EthnicWashCountyVT['MaleEmployedCountEst'] = round(EthnicWashCountyVT['Men'] * EthnicWashCountyVT['EmployedPct']).astype(int)

In [250]:
EthnicWashCountyVT['FemaleEmployedCountEst'] = round(EthnicWashCountyVT['Women'] * EthnicWashCountyVT['EmployedPct']).astype(int)

In [251]:
EthnicWashCountyVT['UnemployedCount'] = round(EthnicWashCountyVT['TotalPop'] * (EthnicWashCountyVT['Unemployment'] * .01)).astype(int)

In [252]:
EthnicWashCountyVT['TotalMaleUnemployedEst'] = round(EthnicWashCountyVT['Men'] * (EthnicWashCountyVT['Unemployment'] * .01)).astype(int)

In [253]:
EthnicWashCountyVT['TotalFemaleUnemployedEst'] = round(EthnicWashCountyVT['Women'] * (EthnicWashCountyVT['Unemployment'] * .01)).astype(int)

In [254]:
EthnicWashCountyVT['TotalPrivateWorkCount'] = round(EthnicWashCountyVT['TotalPop'] * (EthnicWashCountyVT['PrivateWork'] * .01)).astype(int)

In [255]:
EthnicWashCountyVT['TotalSelfEmployedCount'] = round(EthnicWashCountyVT['TotalPop'] * (EthnicWashCountyVT['SelfEmployed'] * .01)).astype(int)

In [256]:
EthnicWashCountyVT['TotalProfessionalCount'] = round(EthnicWashCountyVT['TotalPop'] * (EthnicWashCountyVT['Professional'] * .01)).astype(int)

In [257]:
EthnicWashCountyVT['TotalServiceCount'] = round(EthnicWashCountyVT['TotalPop'] * (EthnicWashCountyVT['Service'] * .01)).astype(int)

In [258]:
EthnicWashCountyVT['TotalOfficeCount'] = round(EthnicWashCountyVT['TotalPop'] * (EthnicWashCountyVT['Office'] * .01)).astype(int)

In [259]:
EthnicWashCountyVT['TotalConstructionCount'] = round(EthnicWashCountyVT['TotalPop'] * (EthnicWashCountyVT['Construction'] * .01)).astype(int)

In [260]:
EthnicWashCountyVT['TotalProductionCount'] = round(EthnicWashCountyVT['TotalPop'] * (EthnicWashCountyVT['Production'] * .01)).astype(int)

In [261]:
EthnicWashCountyVT.head()

,TotalPop,Men,Women,White,Hispanic,Black,Native,Asian,Pacific,Citizen,...,UnemployedCount,TotalMaleUnemployedEst,TotalFemaleUnemployedEst,TotalPrivateWorkCount,TotalSelfEmployedCount,TotalProfessionalCount,TotalServiceCount,TotalOfficeCount,TotalConstructionCount,TotalProductionCount
0,4385,2190,2195,94.3,1.6,0.8,0.1,0.6,0.0,3313,...,298,149,149,2991,737,1723,596,1022,662,381
1,2395,1246,1149,92.9,3.0,0.0,0.0,0.6,0.0,1945,...,103,54,49,1605,311,999,350,575,331,144
2,2811,1416,1395,94.1,1.3,0.6,0.4,0.6,0.0,2118,...,112,57,56,1796,498,1380,340,517,351,225
3,5089,2556,2533,96.1,0.9,0.0,0.0,0.9,0.0,4180,...,326,164,162,3842,366,2254,830,1023,560,427
4,3060,1549,1511,93.4,3.0,0.0,2.3,0.9,0.0,2428,...,110,56,54,2206,226,1356,514,624,297,269

In [262]:
EthnicWashCountyVT.columns

Index(['TotalPop', 'Men', 'Women', 'White', 'Hispanic', 'Black', 'Native',
       'Asian', 'Pacific', 'Citizen', 'Income', 'Employed', 'PrivateWork',
       'SelfEmployed', 'Unemployment', 'Professional', 'Service', 'Office',
       'Construction', 'Production', 'WhiteTotalPop', 'WhiteMaleTotalPop',
       'WhiteFemaleTotalPop', 'HispanicTotalPop', 'HispanicMaleTotalPop',
       'HispanicFemaleTotalPop', 'BlackTotalPop', 'BlackMaleTotalPop',
       'BlackFemaleTotalPop', 'NativeTotalPop', 'NativeMaleTotalPop',
       'NativeFemaleTotalPop', 'AsianTotalPop', 'AsianMaleTotalPop',
       'AsianFemaleTotalPop', 'PacificTotalPop', 'PacificMaleTotalPop',
       'PacificFemaleTotalPop', 'TotalMalePercentage', 'TotalFemalePercentage',
       'TotalWhitePopPercentage', 'TotalWhiteMalePercentage',
       'TotalWhiteFemalePercentage', 'TotalHispanicPopPercentage',
       'TotalHispanicMalePercentage', 'TotalHispanicFemalePercentage',
       'TotalBlackPopPercentage', 'TotalBlackMalePercentage',
       'TotalBlackFemalePercentage', 'TotalNativePercentage',
       'TotalAsianPopPercentage', 'TotalAsianMalePercentage',
       'TotalAsianFemalePercentage', 'TotalPacificPopPercentage',
       'TotalPacificMalePercentage', 'TotalPacificFemalePercentage',
       'NonCitizen', 'CitizenPercentage', 'NonCitizenPercentage',
       'EmployedPct', 'MaleEmployedCountEst', 'FemaleEmployedCountEst',
       'UnemployedCount', 'TotalMaleUnemployedEst', 'TotalFemaleUnemployedEst',
       'TotalPrivateWorkCount', 'TotalSelfEmployedCount',
       'TotalProfessionalCount', 'TotalServiceCount', 'TotalOfficeCount',
       'TotalConstructionCount', 'TotalProductionCount'],
      dtype='object')

In [263]:
EthnicWashCountyVTSums = pd.DataFrame(data = 
            EthnicWashCountyVT, columns=['TotalPop', 'Men', 'Women', 'WhiteTotalPop', 'WhiteMaleTotalPop',
                                         'WhiteFemaleTotalPop', 'HispanicTotalPop', 'HispanicMaleTotalPop',
                                         'HispanicFemaleTotalPop', 'BlackTotalPop', 'BlackMaleTotalPop',
                                         'BlackFemaleTotalPop', 'NativeTotalPop', 'NativeMaleTotalPop',
                                         'NativeFemaleTotalPop', 'AsianTotalPop', 'AsianMaleTotalPop',
                                         'AsianFemaleTotalPop', 'PacificTotalPop', 'PacificMaleTotalPop',
                                         'PacificFemaleTotalPop', 'Citizen','NonCitizen', 'MaleEmployedCountEst', 
                                         'FemaleEmployedCountEst','Employed','UnemployedCount', 'TotalMaleUnemployedEst',
                                         'TotalFemaleUnemployedEst','TotalPrivateWorkCount', 'TotalSelfEmployedCount',
                                         'TotalProfessionalCount', 'TotalServiceCount',                                                                          
                                         'TotalOfficeCount','TotalConstructionCount', 'TotalProductionCount'])
EthnicWashCountyVTSums.head(19)

,TotalPop,Men,Women,WhiteTotalPop,WhiteMaleTotalPop,WhiteFemaleTotalPop,HispanicTotalPop,HispanicMaleTotalPop,HispanicFemaleTotalPop,BlackTotalPop,...,UnemployedCount,TotalMaleUnemployedEst,TotalFemaleUnemployedEst,TotalPrivateWorkCount,TotalSelfEmployedCount,TotalProfessionalCount,TotalServiceCount,TotalOfficeCount,TotalConstructionCount,TotalProductionCount
0,4385,2190,2195,4135,2065,2070,70,35,35,35,...,298,149,149,2991,737,1723,596,1022,662,381
1,2395,1246,1149,2225,1158,1067,72,37,34,0,...,103,54,49,1605,311,999,350,575,331,144
2,2811,1416,1395,2645,1332,1313,37,18,18,17,...,112,57,56,1796,498,1380,340,517,351,225
3,5089,2556,2533,4891,2456,2434,46,23,23,0,...,326,164,162,3842,366,2254,830,1023,560,427
4,3060,1549,1511,2858,1447,1411,92,46,45,0,...,110,56,54,2206,226,1356,514,624,297,269
5,2850,1399,1451,2662,1307,1355,20,10,10,14,...,202,99,103,1995,279,1129,453,673,333,259
6,2264,1091,1173,2069,997,1072,57,27,29,43,...,258,124,134,1542,251,1506,299,346,41,70
7,1462,718,744,1409,692,717,13,6,7,0,...,98,48,50,969,142,782,230,357,54,41
8,2311,999,1312,2195,949,1246,0,0,0,42,...,53,23,30,1618,153,1229,314,478,106,183
9,1675,782,893,1591,743,848,30,14,16,2,...,34,16,18,1129,111,879,164,462,85,85
10,2610,1169,1441,2404,1077,1327,138,62,76,29,...,86,39,48,1801,222,1391,253,569,177,219
11,4154,1907,2247,4063,1865,2198,0,0,0,0,...,233,107,126,3032,228,1579,606,1354,270,349
12,4731,2113,2618,4267,1906,2361,142,63,79,227,...,369,165,204,3950,241,1580,828,1367,274,681
13,3902,1878,2024,3769,1814,1955,43,21,22,12,...,215,103,111,2798,402,1545,519,1217,312,308
14,3988,2091,1897,3769,1976,1793,120,63,57,24,...,116,61,55,3214,136,1360,734,1001,327,566
15,6898,3817,3081,6463,3577,2887,207,115,92,55,...,172,95,77,4725,552,2828,1159,1614,648,648
16,1615,842,773,1584,826,758,0,0,0,0,...,21,11,10,1255,213,690,326,376,179,44
17,1701,799,902,1623,762,861,22,10,12,5,...,32,15,17,1230,201,760,316,383,148,94
18,1231,620,611,1199,604,595,0,0,0,4,...,22,11,11,937,130,645,170,194,124,98

In [264]:
EthnicWashCountyVTSums.sum()

TotalPop                    59132
Men                         29182
Women                       29950
WhiteTotalPop               55821
WhiteMaleTotalPop           27553
WhiteFemaleTotalPop         28268
HispanicTotalPop             1109
HispanicMaleTotalPop          550
HispanicFemaleTotalPop        555
BlackTotalPop                 509
BlackMaleTotalPop             241
BlackFemaleTotalPop           269
NativeTotalPop                153
NativeMaleTotalPop             74
NativeFemaleTotalPop           80
AsianTotalPop                 465
AsianMaleTotalPop             234
AsianFemaleTotalPop           231
PacificTotalPop                 6
PacificMaleTotalPop             3
PacificFemaleTotalPop           3
Citizen                     46741
NonCitizen                  12391
MaleEmployedCountEst        15704
FemaleEmployedCountEst      16070
Employed                    31774
UnemployedCount              2860
TotalMaleUnemployedEst       1397
TotalFemaleUnemployedEst     1464
TotalPrivateWorkCount       42635
TotalSelfEmployedCount       5399
TotalProfessionalCount      25615
TotalServiceCount            9001
TotalOfficeCount            14152
TotalConstructionCount       5279
TotalProductionCount         5091
dtype: int64

In [265]:
EthnicWashCountyVTPercentiles = pd.DataFrame(data = EthnicWashCountyVT, columns=['White', 'Hispanic', 'Black', 'Native',
       'Asian', 'Pacific',  'PrivateWork',
       'SelfEmployed', 'Unemployment', 'Professional', 'Service', 'Office',
       'Construction', 'Production', 'TotalWhitePopPercentage', 'TotalMalePercentage', 'TotalFemalePercentage',
       'TotalWhiteMalePercentage', 'TotalWhiteFemalePercentage',                                                                          
       'TotalHispanicPopPercentage', 'TotalHispanicMalePercentage',
       'TotalHispanicFemalePercentage', 'TotalBlackPopPercentage',
       'TotalBlackMalePercentage', 'TotalBlackFemalePercentage',
       'TotalAsianPopPercentage', 'TotalAsianMalePercentage',
       'TotalAsianFemalePercentage', 'TotalNativePercentage', 'TotalPacificPopPercentage',
       'TotalPacificMalePercentage', 'TotalPacificFemalePercentage',
       'CitizenPercentage', 'NonCitizenPercentage', 'CitizenPercentage', 
       'NonCitizenPercentage', 'EmployedPct',])

In [266]:
EthnicWashCountyVTPercentiles.head(19)

,White,Hispanic,Black,Native,Asian,Pacific,PrivateWork,SelfEmployed,Unemployment,Professional,...,TotalAsianFemalePercentage,TotalNativePercentage,TotalPacificPopPercentage,TotalPacificMalePercentage,TotalPacificFemalePercentage,CitizenPercentage,NonCitizenPercentage,CitizenPercentage,NonCitizenPercentage,EmployedPct
0,94.3,1.6,0.8,0.1,0.6,0.0,68.2,16.8,6.8,39.3,...,0.002965,0.000912,0.000000,0.000000,0.000000,0.755530,0.244470,0.755530,0.244470,0.500114
1,92.9,3.0,0.0,0.0,0.6,0.0,67.0,13.0,4.3,41.7,...,0.002923,0.000000,0.000000,0.000000,0.000000,0.812109,0.187891,0.812109,0.187891,0.553653
2,94.1,1.3,0.6,0.4,0.6,0.0,63.9,17.7,4.0,49.1,...,0.002846,0.003913,0.000000,0.000000,0.000000,0.753469,0.246531,0.753469,0.246531,0.557809
3,96.1,0.9,0.0,0.0,0.9,0.0,75.5,7.2,6.4,44.3,...,0.004520,0.000000,0.000000,0.000000,0.000000,0.821379,0.178621,0.821379,0.178621,0.610729
4,93.4,3.0,0.0,2.3,0.9,0.0,72.1,7.4,3.6,44.3,...,0.004575,0.022876,0.000000,0.000000,0.000000,0.793464,0.206536,0.793464,0.206536,0.581046
5,93.4,0.7,0.5,0.3,2.4,0.2,70.0,9.8,7.1,39.6,...,0.012281,0.003158,0.002105,0.001053,0.001053,0.813333,0.186667,0.813333,0.186667,0.460351
6,91.4,2.5,1.9,0.0,1.8,0.0,68.1,11.1,11.4,66.5,...,0.009276,0.000000,0.000000,0.000000,0.000000,0.791961,0.208039,0.791961,0.208039,0.534011
7,96.4,0.9,0.0,0.0,1.0,0.0,66.3,9.7,6.7,53.5,...,0.004788,0.000000,0.000000,0.000000,0.000000,0.785910,0.214090,0.785910,0.214090,0.493844
8,95.0,0.0,1.8,0.0,0.0,0.0,70.0,6.6,2.3,53.2,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.796192,0.203808,0.796192,0.203808,0.536132
9,95.0,1.8,0.1,0.0,1.7,0.0,67.4,6.6,2.0,52.5,...,0.008955,0.000000,0.000000,0.000000,0.000000,0.778507,0.221493,0.778507,0.221493,0.494925
10,92.1,5.3,1.1,0.0,0.2,0.0,69.0,8.5,3.3,53.3,...,0.001149,0.000000,0.000000,0.000000,0.000000,0.794253,0.205747,0.794253,0.205747,0.541762
11,97.8,0.0,0.0,0.0,0.0,0.0,73.0,5.5,5.6,38.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.771305,0.228695,0.771305,0.228695,0.505537
12,90.2,3.0,4.8,1.1,0.6,0.0,83.5,5.1,7.8,33.4,...,0.003382,0.010991,0.000000,0.000000,0.000000,0.741281,0.258719,0.741281,0.258719,0.472839
13,96.6,1.1,0.3,0.0,0.0,0.0,71.7,10.3,5.5,39.6,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.765761,0.234239,0.765761,0.234239,0.554587
14,94.5,3.0,0.6,0.0,0.4,0.0,80.6,3.4,2.9,34.1,...,0.002006,0.000000,0.000000,0.000000,0.000000,0.786610,0.213390,0.786610,0.213390,0.578485
15,93.7,3.0,0.8,0.0,1.5,0.0,68.5,8.0,2.5,41.0,...,0.006669,0.000000,0.000000,0.000000,0.000000,0.847927,0.152073,0.847927,0.152073,0.512612
16,98.1,0.0,0.0,0.0,0.7,0.0,77.7,13.2,1.3,42.7,...,0.003096,0.000000,0.000000,0.000000,0.000000,0.791950,0.208050,0.791950,0.208050,0.595046
17,95.4,1.3,0.3,0.4,0.4,0.0,72.3,11.8,1.9,44.7,...,0.002352,0.004115,0.000000,0.000000,0.000000,0.821869,0.178131,0.821869,0.178131,0.620223
18,97.4,0.0,0.3,0.0,1.0,0.0,76.1,10.6,1.8,52.4,...,0.004874,0.000000,0.000000,0.000000,0.000000,0.745735,0.254265,0.745735,0.254265,0.581641

In [267]:
EthnicWashCountyVTSums.to_csv("washcountyvttotals.csv", index=True)

In [268]:
EthnicWashCountyVTPercentiles.to_csv("washcountyvtpercentages.csv", index=True)

In [269]:
EthnicWashCountyVT.to_csv('completewashcountyvtdataset.csv')